apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ebs-csi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/denesbeck/dev-platform.git
    targetRevision: main
    path: argocd/platform/ebs-csi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
